# Generated by Django 5.2.8 on 2025-11-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="DEBORAH", max_length=50, verbose_name="Название сайта"
                    ),
                ),
                (
                    "brand_font",
                    models.CharField(
                        choices=[
                            ("Playfair Display", "Playfair Display (Classic)"),
                            ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                            ("Montserrat", "Montserrat (Modern)"),
                            ("Lato", "Lato (Neutral)"),
                            ("Open Sans", "Open Sans"),
                            ("Roboto", "Roboto"),
                            ("Oswald", "Oswald (Bold)"),
                            ("Merriweather", "Merriweather"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                            ("Didot", "Didot (Fashion)"),
                            ("Bodoni Moda", "Bodoni Moda"),
                            ("Tenor Sans", "Tenor Sans"),
                            ("Italiana", "Italiana"),
                            ("Prata", "Prata"),
                            ("Marcellus", "Marcellus"),
                            ("Comfortaa", "Comfortaa"),
                            ("Caveat", "Caveat"),
                        ],
                        default="Playfair Display",
                        max_length=50,
                        verbose_name="Шрифт Лого",
                    ),
                ),
                (
                    "headings_font",
                    models.CharField(
                        choices=[
                            ("Playfair Display", "Playfair Display (Classic)"),
                            ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                            ("Montserrat", "Montserrat (Modern)"),
                            ("Lato", "Lato (Neutral)"),
                            ("Open Sans", "Open Sans"),
                            ("Roboto", "Roboto"),
                            ("Oswald", "Oswald (Bold)"),
                            ("Merriweather", "Merriweather"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                            ("Didot", "Didot (Fashion)"),
                            ("Bodoni Moda", "Bodoni Moda"),
                            ("Tenor Sans", "Tenor Sans"),
                            ("Italiana", "Italiana"),
                            ("Prata", "Prata"),
                            ("Marcellus", "Marcellus"),
                            ("Comfortaa", "Comfortaa"),
                            ("Caveat", "Caveat"),
                        ],
                        default="Playfair Display",
                        max_length=50,
                        verbose_name="Шрифт Заголовков",
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        choices=[
                            ("Playfair Display", "Playfair Display (Classic)"),
                            ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                            ("Montserrat", "Montserrat (Modern)"),
                            ("Lato", "Lato (Neutral)"),
                            ("Open Sans", "Open Sans"),
                            ("Roboto", "Roboto"),
                            ("Oswald", "Oswald (Bold)"),
                            ("Merriweather", "Merriweather"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                            ("Didot", "Didot (Fashion)"),
                            ("Bodoni Moda", "Bodoni Moda"),
                            ("Tenor Sans", "Tenor Sans"),
                            ("Italiana", "Italiana"),
                            ("Prata", "Prata"),
                            ("Marcellus", "Marcellus"),
                            ("Comfortaa", "Comfortaa"),
                            ("Caveat", "Caveat"),
                        ],
                        default="Lato",
                        max_length=50,
                        verbose_name="Шрифт Текста",
                    ),
                ),
                (
                    "menu_font",
                    models.CharField(
                        choices=[
                            ("Playfair Display", "Playfair Display (Classic)"),
                            ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                            ("Montserrat", "Montserrat (Modern)"),
                            ("Lato", "Lato (Neutral)"),
                            ("Open Sans", "Open Sans"),
                            ("Roboto", "Roboto"),
                            ("Oswald", "Oswald (Bold)"),
                            ("Merriweather", "Merriweather"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                            ("Didot", "Didot (Fashion)"),
                            ("Bodoni Moda", "Bodoni Moda"),
                            ("Tenor Sans", "Tenor Sans"),
                            ("Italiana", "Italiana"),
                            ("Prata", "Prata"),
                            ("Marcellus", "Marcellus"),
                            ("Comfortaa", "Comfortaa"),
                            ("Caveat", "Caveat"),
                        ],
                        default="Montserrat",
                        max_length=50,
                        verbose_name="Шрифт Меню",
                    ),
                ),
                (
                    "header_bg_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/header/",
                        verbose_name="Фон Шапки",
                    ),
                ),
                (
                    "header_bg_color",
                    models.CharField(
                        default="#ffffff", max_length=20, verbose_name="Цвет Шапки"
                    ),
                ),
                (
                    "hero_bg_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/hero/",
                        verbose_name="Фон Баннера",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Нова Колекція",
                        max_length=100,
                        verbose_name="Заголовок Баннера",
                    ),
                ),
                (
                    "body_bg_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/body/",
                        verbose_name="Фон Сайта",
                    ),
                ),
                (
                    "body_bg_color",
                    models.CharField(
                        default="#f9f9f9", max_length=20, verbose_name="Цвет Фона"
                    ),
                ),
                (
                    "footer_bg_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/footer/",
                        verbose_name="Фон Футера",
                    ),
                ),
                (
                    "footer_bg_color",
                    models.CharField(
                        default="#1a1a1a", max_length=20, verbose_name="Цвет Футера"
                    ),
                ),
                (
                    "footer_text_color",
                    models.CharField(
                        default="#888888", max_length=20, verbose_name="Текст Футера"
                    ),
                ),
                (
                    "nova_poshta_api_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="API Новой Почты"
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="TG Bot Token"
                    ),
                ),
                (
                    "telegram_admin_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TG Admin ID"
                    ),
                ),
                (
                    "wfp_merchant_login",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WayForPay Login"
                    ),
                ),
                (
                    "wfp_secret_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WayForPay Secret"
                    ),
                ),
                (
                    "liqpay_public_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LiqPay Public"
                    ),
                ),
                (
                    "liqpay_private_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LiqPay Private"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="SEO Описание"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, verbose_name="GA4 ID"),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="FB Pixel ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "⚙️ Настройки Сайта",
                "verbose_name_plural": "⚙️ Настройки Сайта",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "city_ref",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ref Города"
                    ),
                ),
                (
                    "nova_poshta",
                    models.CharField(max_length=200, verbose_name="Отделение"),
                ),
                (
                    "warehouse_ref",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ref Отделения"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wayforpay", "WayForPay"),
                            ("liqpay", "LiqPay"),
                            ("cod", "Наложенный"),
                            ("cash", "Наличные"),
                        ],
                        default="cod",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("sent", "Отправлен"),
                            ("done", "Выполнен"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, verbose_name="ТТН"),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="site", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "sizes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=100,
                        verbose_name="Размеры",
                    ),
                ),
                (
                    "colors",
                    models.CharField(blank=True, max_length=200, verbose_name="Цвета"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Фото"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галерея",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
