# Generated by Django 5.2.8 on 2025-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "⚙️ Налаштування Сайту",
                "verbose_name_plural": "⚙️ Налаштування Сайту",
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, verbose_name="Колір"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=20, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Місто"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city_ref",
            field=models.CharField(blank=True, max_length=50, verbose_name="Ref Міста"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Прізвище"),
        ),
        migrations.AlterField(
            model_name="order",
            name="nova_poshta",
            field=models.CharField(max_length=200, verbose_name="Відділення"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wayforpay", "WayForPay (Visa/Master)"),
                    ("liqpay", "LiqPay"),
                    ("cod", "Накладений платіж"),
                    ("cash", "Готівка"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новий"),
                    ("sent", "Відправлено"),
                    ("done", "Виконано"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="warehouse_ref",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ref Відділення"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, max_length=200, verbose_name="Кольори"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Стара ціна",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=100,
                verbose_name="Розміри",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/gallery/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_bg_color",
            field=models.CharField(
                default="#f9f9f9",
                help_text="Use hex like #f9f9f9",
                max_length=20,
                verbose_name="Колір Фону",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Lato",
                max_length=50,
                verbose_name="Шрифт Тексту",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Лого",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_bg_color",
            field=models.CharField(
                default="#1a1a1a",
                help_text="Use hex like #f9f9f9",
                max_length=20,
                verbose_name="Колір Футера",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text_color",
            field=models.CharField(
                default="#888888",
                help_text="Use hex like #f9f9f9",
                max_length=20,
                verbose_name="Текст Футера",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="header_bg_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Use hex like #f9f9f9",
                max_length=20,
                verbose_name="Колір Шапки",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="headings_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Заголовків",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_bg_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/hero/", verbose_name="Фон Банера"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                default="Нова Колекція", max_length=100, verbose_name="Заголовок Банера"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="menu_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Montserrat",
                max_length=50,
                verbose_name="Шрифт Меню",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.TextField(blank=True, verbose_name="SEO Опис"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="nova_poshta_api_key",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="API Нової Пошти"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="DEBORAH", max_length=50, verbose_name="Назва сайту"
            ),
        ),
    ]
