# Generated by Django 5.2.8 on 2025-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wayforpay", "WayForPay"),
                    ("liqpay", "LiqPay"),
                    ("cod", "Накладений платіж"),
                    ("cash", "Готівка"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(
                blank=True,
                help_text="Через кому (Black,Red)",
                max_length=200,
                verbose_name="Кольори",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                help_text="Через кому (S,M,L)",
                max_length=100,
                verbose_name="Розміри",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_bg_color",
            field=models.CharField(
                default="#f9f9f9", max_length=20, verbose_name="Колір Фону"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_bg_color",
            field=models.CharField(
                default="#1a1a1a", max_length=20, verbose_name="Колір Футера"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text_color",
            field=models.CharField(
                default="#888888", max_length=20, verbose_name="Текст Футера"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="header_bg_color",
            field=models.CharField(
                default="#ffffff", max_length=20, verbose_name="Колір Шапки"
            ),
        ),
    ]
