# Generated by Django 5.2.8 on 2025-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_order_payment_method_alter_product_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright",
            field=models.CharField(
                blank=True,
                default="2025 All rights reserved.",
                max_length=100,
                verbose_name="Копирайт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_main_text",
            field=models.CharField(
                blank=True,
                default="Premium Quality Store",
                max_length=200,
                verbose_name="Текст в футере (подвал)",
            ),
        ),
    ]
