# Generated by Django 5.2.8 on 2025-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_sitesettings_footer_copyright_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="youtube_video",
            field=models.CharField(
                blank=True,
                help_text="Вставьте полную ссылку (например: https://www.youtube.com/watch?v=dQw4w9WgXcQ)",
                max_length=200,
                verbose_name="Ссылка на YouTube",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_facebook",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Facebook (ссылка)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_instagram",
            field=models.CharField(
                blank=True,
                help_text="https://instagram.com/...",
                max_length=200,
                verbose_name="Instagram (ссылка)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_telegram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Telegram (ссылка)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_main_text",
            field=models.CharField(
                blank=True,
                default="Premium Quality Store",
                max_length=200,
                verbose_name="Текст в футере",
            ),
        ),
    ]
