# Generated by Django 5.2.8 on 2025-11-24 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_review_options_review_author_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Відгук",
                "verbose_name_plural": "⭐ Відгуки",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="fake_count",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Скільки відгуків створити",
                verbose_name="Кількість відгуків",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="generate_fake",
            field=models.BooleanField(
                default=False,
                help_text="Поставте галочку і збережіть, щоб додати відгуки",
                verbose_name="➕ Згенерувати фейкові відгуки?",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="youtube_video",
            field=models.CharField(
                blank=True,
                help_text="Вставьте полную ссылку",
                max_length=200,
                verbose_name="Ссылка на YouTube",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Имя автора"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
