# Generated by Django 5.2.8 on 2025-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_review_options_product_fake_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_body",
            field=models.IntegerField(
                default=16, help_text="Наприклад: 16", verbose_name="Розмір Тексту (px)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_h1",
            field=models.IntegerField(
                default=32,
                help_text="Наприклад: 32",
                verbose_name="Розмір Заголовків H1 (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_logo",
            field=models.IntegerField(
                default=28, help_text="Наприклад: 28", verbose_name="Розмір Лого (px)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_menu",
            field=models.IntegerField(
                default=13, help_text="Наприклад: 13", verbose_name="Розмір Меню (px)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fake_count",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Кількість відгуків"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="generate_fake",
            field=models.BooleanField(
                default=False, verbose_name="➕ Згенерувати фейкові відгуки?"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="youtube_video",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ссылка на YouTube"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="social_instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram (ссылка)"
            ),
        ),
    ]
