# Generated by Django 5.2.8 on 2025-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_sitesettings_font_size_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="btn_main_bg",
            field=models.CharField(
                default="#000000",
                help_text="Колір кнопки 'Купити' або активного фільтру",
                max_length=20,
                verbose_name="Фон кнопок (активні)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="btn_main_text",
            field=models.CharField(
                default="#ffffff", max_length=20, verbose_name="Текст кнопок (активні)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_buttons",
            field=models.IntegerField(
                default=14,
                help_text="Розмір тексту в кнопках 'Всі', 'Сукні'...",
                verbose_name="Текст кнопок/фільтрів (px)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_price",
            field=models.IntegerField(default=16, verbose_name="Ціна товару (px)"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="font_size_product_name",
            field=models.IntegerField(
                default=16, verbose_name="Назва товару в каталозі (px)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_size_body",
            field=models.IntegerField(default=16, verbose_name="Основний текст (px)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_size_h1",
            field=models.IntegerField(default=32, verbose_name="Заголовок H1 (px)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_size_logo",
            field=models.IntegerField(default=28, verbose_name="Логотип (px)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="font_size_menu",
            field=models.IntegerField(default=13, verbose_name="Меню в шапці (px)"),
        ),
    ]
