# Generated by Django 5.2.8 on 2025-11-26 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_sitesettings_body_font_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TickerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="site/ticker/", verbose_name="Банер для стрічки"
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Посилання (опціонально)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
            ],
            options={
                "verbose_name": "Банер стрічки",
                "verbose_name_plural": "🎞️ Біжуча стрічка (Банери)",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Відгук", "verbose_name_plural": "Відгуки"},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fake_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="generate_fake",
        ),
        migrations.RemoveField(
            model_name="product",
            name="youtube_video",
        ),
        migrations.RemoveField(
            model_name="review",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="btn_main_bg",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="btn_main_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_body",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_buttons",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_h1",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_logo",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_menu",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_price",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_size_product_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_copyright",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_main_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="social_facebook",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="social_instagram",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="social_telegram",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_ticker",
            field=models.BooleanField(
                default=True, verbose_name="Показувати біжучу стрічку"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_bg_color",
            field=models.CharField(
                default="#000000", max_length=20, verbose_name="Фон стрічки (HEX)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wayforpay", "WayForPay"),
                    ("liqpay", "LiqPay"),
                    ("cod", "Накладений"),
                    ("cash", "Готівка"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, max_length=200, verbose_name="Кольори"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=100,
                verbose_name="Розміри",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/gallery/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Lato",
                max_length=50,
                verbose_name="Шрифт Тексту",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Лого",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="headings_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Заголовків",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="menu_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Montserrat",
                max_length=50,
                verbose_name="Шрифт Меню",
            ),
        ),
    ]
