# Generated by Django 5.2.8 on 2025-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_tickeritem_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickeritem",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: /product/5/ або https://example.com",
                max_length=500,
                verbose_name="Посилання (опціонально)",
            ),
        ),
    ]
