# Generated by Django 5.2.8 on 2025-11-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_tickeritem_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TickerItem",
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="show_ticker",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="ticker_bg_color",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, verbose_name="Колір"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=20, verbose_name="Розмір"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wayforpay", "WayForPay"),
                    ("liqpay", "LiqPay"),
                    ("cod", "Накладений платіж"),
                    ("cash", "Готівка"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(
                blank=True,
                help_text="Через кому (Black,Red)",
                max_length=200,
                verbose_name="Кольори",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                help_text="Через кому (S,M,L)",
                max_length=100,
                verbose_name="Розміри",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/gallery/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Lato",
                max_length=50,
                verbose_name="Шрифт Тексту",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Лого",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="headings_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Заголовків",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="menu_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display"),
                    ("Cormorant Garamond", "Cormorant Garamond"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Montserrat",
                max_length=50,
                verbose_name="Шрифт Меню",
            ),
        ),
    ]
