# Generated by Django 5.2.8 on 2025-11-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_delete_tickeritem_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Назва сторінки"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Наприклад: summer-sale або new-collection",
                        max_length=200,
                        unique=True,
                        verbose_name="URL (slug)",
                    ),
                ),
                (
                    "background_type",
                    models.CharField(
                        choices=[
                            ("color", "Колір"),
                            ("gradient", "Градієнт"),
                            ("image", "Зображення"),
                        ],
                        default="color",
                        max_length=20,
                        verbose_name="Тип фону",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        default="#ffffff",
                        max_length=20,
                        verbose_name="Колір фону",
                    ),
                ),
                (
                    "background_gradient",
                    models.CharField(
                        blank=True,
                        help_text="CSS градієнт, наприклад: linear-gradient(to right, #667eea, #764ba2)",
                        max_length=200,
                        verbose_name="Градієнт",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="landing/backgrounds/",
                        verbose_name="Зображення фону",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Заголовок"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="SEO Опис"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Промо-сторінка",
                "verbose_name_plural": "📄 Промо-сторінки (Landing Pages)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Відгук", "verbose_name_plural": "Відгуки"},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_ticker",
            field=models.BooleanField(
                default=True, verbose_name="Показувати біжучу стрічку"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_bg_color",
            field=models.CharField(
                default="#000000", max_length=20, verbose_name="Фон стрічки (HEX)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wayforpay", "WayForPay"),
                    ("liqpay", "LiqPay"),
                    ("cod", "Накладений"),
                    ("cash", "Готівка"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, max_length=200, verbose_name="Кольори"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=100,
                verbose_name="Розміри",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/gallery/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Lato",
                max_length=50,
                verbose_name="Шрифт Тексту",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Лого",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="headings_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Playfair Display",
                max_length=50,
                verbose_name="Шрифт Заголовків",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="menu_font",
            field=models.CharField(
                choices=[
                    ("Playfair Display", "Playfair Display (Classic)"),
                    ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                    ("Montserrat", "Montserrat (Modern)"),
                    ("Lato", "Lato (Neutral)"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Oswald", "Oswald (Bold)"),
                    ("Merriweather", "Merriweather"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Didot", "Didot (Fashion)"),
                    ("Bodoni Moda", "Bodoni Moda"),
                    ("Tenor Sans", "Tenor Sans"),
                    ("Italiana", "Italiana"),
                    ("Prata", "Prata"),
                    ("Marcellus", "Marcellus"),
                    ("Comfortaa", "Comfortaa"),
                    ("Caveat", "Caveat"),
                ],
                default="Montserrat",
                max_length=50,
                verbose_name="Шрифт Меню",
            ),
        ),
        migrations.CreateModel(
            name="LandingBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовий блок"),
                            ("image", "Зображення"),
                            ("button", "Кнопка"),
                            ("products", "Товари"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип блоку",
                    ),
                ),
                ("text_content", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "text_font",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Playfair Display", "Playfair Display (Classic)"),
                            ("Cormorant Garamond", "Cormorant Garamond (Luxury)"),
                            ("Montserrat", "Montserrat (Modern)"),
                            ("Lato", "Lato (Neutral)"),
                            ("Open Sans", "Open Sans"),
                            ("Roboto", "Roboto"),
                            ("Oswald", "Oswald (Bold)"),
                            ("Merriweather", "Merriweather"),
                            ("Raleway", "Raleway"),
                            ("Nunito", "Nunito"),
                            ("Didot", "Didot (Fashion)"),
                            ("Bodoni Moda", "Bodoni Moda"),
                            ("Tenor Sans", "Tenor Sans"),
                            ("Italiana", "Italiana"),
                            ("Prata", "Prata"),
                            ("Marcellus", "Marcellus"),
                            ("Comfortaa", "Comfortaa"),
                            ("Caveat", "Caveat"),
                        ],
                        default="Lato",
                        max_length=50,
                        verbose_name="Шрифт",
                    ),
                ),
                (
                    "text_size",
                    models.IntegerField(
                        blank=True, default=16, verbose_name="Розмір шрифту (px)"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        default="#000000",
                        max_length=20,
                        verbose_name="Колір тексту",
                    ),
                ),
                (
                    "text_alignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Ліворуч"),
                            ("center", "По центру"),
                            ("right", "Праворуч"),
                        ],
                        default="center",
                        max_length=10,
                        verbose_name="Вирівнювання",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="landing/blocks/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(
                        blank=True,
                        default=100,
                        help_text="Від 10 до 100",
                        verbose_name="Ширина зображення (%)",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Посилання кнопки"
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        blank=True,
                        default="#000000",
                        max_length=20,
                        verbose_name="Колір кнопки",
                    ),
                ),
                (
                    "products_limit",
                    models.IntegerField(
                        blank=True, default=4, verbose_name="Кількість товарів"
                    ),
                ),
                (
                    "position_top",
                    models.IntegerField(
                        default=10,
                        help_text="Від 0 до 100",
                        verbose_name="Відступ зверху (%)",
                    ),
                ),
                (
                    "position_left",
                    models.IntegerField(
                        default=10,
                        help_text="Від 0 до 100",
                        verbose_name="Відступ зліва (%)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "products_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.category",
                        verbose_name="Категорія товарів",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="store.landingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок контенту",
                "verbose_name_plural": "Блоки контенту",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TickerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="site/ticker/", verbose_name="Банер для стрічки"
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("url", "URL"), ("landing", "Промо-сторінка")],
                        default="url",
                        max_length=20,
                        verbose_name="Тип посилання",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Наприклад: /product/5/ або https://example.com",
                        max_length=500,
                        verbose_name="URL посилання",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "link_landing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.landingpage",
                        verbose_name="Промо-сторінка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банер стрічки",
                "verbose_name_plural": "🎞️ Біжуча стрічка (Банери)",
                "ordering": ["order"],
            },
        ),
    ]
